before_script:
- ssh-keyscan -H gitlab.cirici.com > ~/.ssh/known_hosts
- curl -sL https://deb.nodesource.com/setup_4.x | bash -
- phpdismod xdebug
- composer self-update
- composer --no-interaction --prefer-source install
- phpenmod xdebug

stages:
- test7.0
- test5.6

test:7.0:
  image: ciricihq/php:7.0
  script:
  - ./vendor/bin/phpunit --coverage-text --colors=never
  - ./vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests

test:5.6:
  image: ciricihq/php:5.6
  script:
  - ./vendor/bin/phpunit --coverage-text --colors=never
